version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ivoglent/php7-nginx:latest
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./bin/start.sh:/usr/local/bin/start.sh

    environment:
      - ENV_SERVER_NAME=forever.localhost